#!/usr/bin/env bash
# Generate telephony/asterisk/pjsip.conf from .env — the only file holding SIP secrets.
# Gitignored on purpose: never hand-edit, never commit. Re-run after changing .env.
#
#   Telnyx:  SIP_TRUNK_HOST=sip.telnyx.com
#   Zadarma: SIP_TRUNK_HOST=pbx.zadarma.com
#   Both:    SIP_USER, SIP_PASSWORD, PUBLIC_IP (public IPv4 of this host)
#
# No SIP_* set → softphone-only config (lab default, unchanged behaviour).
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then set -a; . ./.env; set +a; fi

OUT=telephony/asterisk/pjsip.conf
PUBLIC_IP="${PUBLIC_IP:-}"
SIP_USER="${SIP_USER:-}"
SIP_PASSWORD="${SIP_PASSWORD:-}"
SIP_TRUNK_HOST="${SIP_TRUNK_HOST:-}"
SOFTPHONE_PASSWORD="${SOFTPHONE_PASSWORD:-hotline-lab}"

if [ -n "$PUBLIC_IP" ] && [ "$SOFTPHONE_PASSWORD" = "hotline-lab" ]; then
  echo "WARN: public host with default softphone password — set SOFTPHONE_PASSWORD in .env" >&2
fi

{
  echo "; GENERATED by scripts/setup-trunk.sh — do not edit, do not commit."
  echo
  echo "[udp-transport]"
  echo "type=transport"
  echo "protocol=udp"
  echo "bind=0.0.0.0"
  # Docker bridge + normal LAN ranges, so a handset on wifi is not treated as external.
  echo "local_net=172.16.0.0/12"
  echo "local_net=10.0.0.0/8"
  echo "local_net=192.168.0.0/16"
  if [ -n "$PUBLIC_IP" ]; then
    # Without these, a public host answers but audio goes nowhere (one-way / dead air).
    echo "external_signaling_address=$PUBLIC_IP"
    echo "external_media_address=$PUBLIC_IP"
  fi

  if [ -n "$SIP_USER" ] && [ -n "$SIP_PASSWORD" ] && [ -n "$SIP_TRUNK_HOST" ]; then
    cat <<EOF

; --- Trunk: $SIP_TRUNK_HOST ---
[trunk_auth]
type=auth
auth_type=userpass
username=$SIP_USER
password=$SIP_PASSWORD

[trunk]
type=registration
transport=udp-transport
outbound_auth=trunk_auth
server_uri=sip:$SIP_TRUNK_HOST
client_uri=sip:$SIP_USER@$SIP_TRUNK_HOST
retry_interval=60
expiration=300
contact_user=$SIP_USER

[trunk]
type=aor
contact=sip:$SIP_TRUNK_HOST

[trunk]
type=endpoint
transport=udp-transport
context=from-trunk
disallow=all
allow=ulaw
allow=alaw
outbound_auth=trunk_auth
aors=trunk
from_user=$SIP_USER
from_domain=$SIP_TRUNK_HOST
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[trunk]
type=identify
endpoint=trunk
match=$SIP_TRUNK_HOST
EOF
  else
    echo
    echo "; No trunk — set SIP_USER / SIP_PASSWORD / SIP_TRUNK_HOST in .env and re-run."
  fi

  cat <<EOF

; --- Local softphone (lab) ---
[hotline-auth]
type=auth
auth_type=userpass
username=hotline
password=$SOFTPHONE_PASSWORD

[hotline]
type=aor
max_contacts=3

[hotline]
type=endpoint
transport=udp-transport
context=from-trunk
disallow=all
allow=ulaw
allow=alaw
auth=hotline-auth
aors=hotline
direct_media=no
; A real handset sits behind wifi/Docker NAT — without these, audio is one-way.
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
EOF
} >"$OUT"

if [ -n "$SIP_TRUNK_HOST" ]; then
  echo "wrote $OUT — trunk $SIP_TRUNK_HOST as $SIP_USER${PUBLIC_IP:+ (public $PUBLIC_IP)}"
else
  echo "wrote $OUT — softphone only (no SIP_* in .env)"
fi
